# IBM Capston Project-Car Collision Severity Prediction

In [5]:
# Import pandas library
import pandas as pd
import numpy as np
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix

# Read the file {here file has been read from my local store,reviewer can download the dataset and import from own storage}, and assign it to variable "df"
other_path = "S:/Coursera IBM Data Science Professional Certificate/9. Applied Data Science Capstone/Week 1/Data-Collisions.csv"
df = pd.read_csv(other_path)
df.head(5)

C:\Users\naman\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (33) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY REPORTNO  \
0             2 -122.323148  47.703140         1    1307       1307  3502005   
1             1 -122.347294  47.647172         2   52200      52200  2607959   
2             1 -122.334540  47.607871         3   26700      26700  1482393   
3             1 -122.334803  47.604803         4    1144       1144  3503937   
4             2 -122.306426  47.545739         5   17700      17700  1807429   

    STATUS      ADDRTYPE   INTKEY      ...      ROADCOND  \
0  Matched  Intersection  37475.0      ...           Wet   
1  Matched         Block      NaN      ...           Wet   
2  Matched         Block      NaN      ...           Dry   
3  Matched         Block      NaN      ...           Dry   
4  Matched  Intersection  34387.0      ...           Wet   

                 LIGHTCOND PEDROWNOTGRNT  SDOTCOLNUM SPEEDING ST_COLCODE  \
0                 Daylight           NaN         NaN      NaN         10   
1  Dark - Street Lights On           NaN   6354039.0      NaN         11   
2                 Daylight           NaN   4323031.0      NaN         32   
3                 Daylight           NaN         NaN      NaN         23   
4                 Daylight           NaN   4028032.0      NaN         10   

                                          ST_COLDESC  SEGLANEKEY  \
0                                  Entering at angle           0   
1  From same direction - both going straight - bo...           0   
2                             One parked--one moving           0   
3                   From same direction - all others           0   
4                                  Entering at angle           0   

   CROSSWALKKEY  HITPARKEDCAR  
0             0             N  
1             0             N  
2             0             N  
3             0             N  
4             0             N  

[5 rows x 38 columns]

In [45]:
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: objec

In [6]:
df["SEVERITYCODE"].value_counts()

1    136485
2     58188
Name: SEVERITYCODE, dtype: int64

# Dataset Balance

In [7]:
from sklearn.utils import resample
df_max = df[df.SEVERITYCODE==1]
df_min = df[df.SEVERITYCODE==2]

df_max_dsample = resample(df_max,n_samples=58188,random_state=123)

balanced_df = pd.concat([df_max_dsample,df_min])
balanced_df.SEVERITYCODE.value_counts()

2    58188
1    58188
Name: SEVERITYCODE, dtype: int64

In [8]:
balanced_df["WEATHER"].value_counts()

Clear                       67853
Raining                     20572
Overcast                    16757
Unknown                      7050
Snowing                       480
Other                         405
Fog/Smog/Smoke                338
Sleet/Hail/Freezing Rain       75
Blowing Sand/Dirt              29
Severe Crosswind               18
Partly Cloudy                   3
Name: WEATHER, dtype: int64

In [9]:
balanced_df["ROADCOND"].value_counts()

Dry               76055
Wet               29225
Unknown            6927
Ice                 654
Snow/Slush          521
Other                83
Standing Water       73
Sand/Mud/Dirt        48
Oil                  39
Name: ROADCOND, dtype: int64

In [10]:
balanced_df["LIGHTCOND"].value_counts()

Daylight                    71665
Dark - Street Lights On     28817
Unknown                      6248
Dusk                         3649
Dawn                         1495
Dark - No Street Lights       832
Dark - Street Lights Off      693
Other                         129
Dark - Unknown Lighting         9
Name: LIGHTCOND, dtype: int64

# Label Encoding

In [11]:
balanced_df["WEATHER"] = balanced_df["WEATHER"].astype('category')
df.dtypes

SEVERITYCODE        int64
X                 float64
Y                 float64
OBJECTID            int64
INCKEY              int64
COLDETKEY           int64
REPORTNO           object
STATUS             object
ADDRTYPE           object
INTKEY            float64
LOCATION           object
EXCEPTRSNCODE      object
EXCEPTRSNDESC      object
SEVERITYCODE.1      int64
SEVERITYDESC       object
COLLISIONTYPE      object
PERSONCOUNT         int64
PEDCOUNT            int64
PEDCYLCOUNT         int64
VEHCOUNT            int64
INCDATE            object
INCDTTM            object
JUNCTIONTYPE       object
SDOT_COLCODE        int64
SDOT_COLDESC       object
INATTENTIONIND     object
UNDERINFL          object
WEATHER            object
ROADCOND           object
LIGHTCOND          object
PEDROWNOTGRNT      object
SDOTCOLNUM        float64
SPEEDING           object
ST_COLCODE         object
ST_COLDESC         object
SEGLANEKEY          int64
CROSSWALKKEY        int64
HITPARKEDCAR       object
dtype: objec

In [12]:
balanced_df["WEATHER_cat"] = balanced_df["WEATHER"].cat.codes
balanced_df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
22536              1 -122.346246  47.617908     26946   40905      40905   
39812              1 -122.316937  47.620520     45068   58413      58413   
25317              1 -122.373595  47.662932     29906   44763      44763   
170256             1 -122.313598  47.569517    190232  251988     252588   
183714             1 -122.303321  47.580505    206555  325075     326575   

       REPORTNO   STATUS      ADDRTYPE   INTKEY     ...       \
22536   2190432  Matched  Intersection  29651.0     ...        
39812   2178396  Matched         Block      NaN     ...        
25317   1794767  Matched  Intersection  25457.0     ...        
170256  3756171  Matched         Block      NaN     ...        
183714  3820889  Matched         Block      NaN     ...        

                      LIGHTCOND PEDROWNOTGRNT SDOTCOLNUM  SPEEDING ST_COLCODE  \
22536   Dark - Street Lights On           NaN  5330033.0       NaN         15   
39812                  Daylight           NaN  6139054.0       NaN         14   
25317                  Daylight           NaN  5068030.0       NaN         10   
170256                 Daylight           NaN        NaN       NaN         23   
183714  Dark - Street Lights On           NaN        NaN       NaN         32   

                                               ST_COLDESC  SEGLANEKEY  \
22536   From same direction - one left turn - one stra...           0   
39812   From same direction - both going straight - on...           0   
25317                                   Entering at angle           0   
170256                   From same direction - all others           0   
183714                             One parked--one moving           0   

        CROSSWALKKEY  HITPARKEDCAR  WEATHER_cat  
22536              0             N            1  
39812              0             N            1  
25317              0             N            1  
170256             0             N            4  
183714             0             N            1  

[5 rows x 39 columns]

In [13]:
balanced_df["ROADCOND"] = balanced_df["ROADCOND"].astype('category')
balanced_df.dtypes
balanced_df["ROADCOND_cat"] = balanced_df["ROADCOND"].cat.codes
balanced_df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
22536              1 -122.346246  47.617908     26946   40905      40905   
39812              1 -122.316937  47.620520     45068   58413      58413   
25317              1 -122.373595  47.662932     29906   44763      44763   
170256             1 -122.313598  47.569517    190232  251988     252588   
183714             1 -122.303321  47.580505    206555  325075     326575   

       REPORTNO   STATUS      ADDRTYPE   INTKEY      ...      PEDROWNOTGRNT  \
22536   2190432  Matched  Intersection  29651.0      ...                NaN   
39812   2178396  Matched         Block      NaN      ...                NaN   
25317   1794767  Matched  Intersection  25457.0      ...                NaN   
170256  3756171  Matched         Block      NaN      ...                NaN   
183714  3820889  Matched         Block      NaN      ...                NaN   

       SDOTCOLNUM SPEEDING  ST_COLCODE  \
22536   5330033.0      NaN          15   
39812   6139054.0      NaN          14   
25317   5068030.0      NaN          10   
170256        NaN      NaN          23   
183714        NaN      NaN          32   

                                               ST_COLDESC SEGLANEKEY  \
22536   From same direction - one left turn - one stra...          0   
39812   From same direction - both going straight - on...          0   
25317                                   Entering at angle          0   
170256                   From same direction - all others          0   
183714                             One parked--one moving          0   

        CROSSWALKKEY  HITPARKEDCAR  WEATHER_cat  ROADCOND_cat  
22536              0             N            1             8  
39812              0             N            1             0  
25317              0             N            1             0  
170256             0             N            4             0  
183714             0             N            1             0  

[5 rows x 40 columns]

In [14]:
balanced_df["LIGHTCOND"] = balanced_df["LIGHTCOND"].astype('category')
balanced_df.dtypes
balanced_df["LIGHTCOND_cat"] = balanced_df["LIGHTCOND"].cat.codes
balanced_df.head()

SEVERITYCODE           X          Y  OBJECTID  INCKEY  COLDETKEY  \
22536              1 -122.346246  47.617908     26946   40905      40905   
39812              1 -122.316937  47.620520     45068   58413      58413   
25317              1 -122.373595  47.662932     29906   44763      44763   
170256             1 -122.313598  47.569517    190232  251988     252588   
183714             1 -122.303321  47.580505    206555  325075     326575   

       REPORTNO   STATUS      ADDRTYPE   INTKEY      ...       SDOTCOLNUM  \
22536   2190432  Matched  Intersection  29651.0      ...        5330033.0   
39812   2178396  Matched         Block      NaN      ...        6139054.0   
25317   1794767  Matched  Intersection  25457.0      ...        5068030.0   
170256  3756171  Matched         Block      NaN      ...              NaN   
183714  3820889  Matched         Block      NaN      ...              NaN   

       SPEEDING ST_COLCODE                                         ST_COLDESC  \
22536       NaN         15  From same direction - one left turn - one stra...   
39812       NaN         14  From same direction - both going straight - on...   
25317       NaN         10                                  Entering at angle   
170256      NaN         23                   From same direction - all others   
183714      NaN         32                             One parked--one moving   

       SEGLANEKEY CROSSWALKKEY  HITPARKEDCAR  WEATHER_cat  ROADCOND_cat  \
22536           0            0             N            1             8   
39812           0            0             N            1             0   
25317           0            0             N            1             0   
170256          0            0             N            4             0   
183714          0            0             N            1             0   

        LIGHTCOND_cat  
22536               2  
39812               5  
25317               5  
170256              5  
183714              2  

[5 rows x 41 columns]

In [15]:
balanced_df.dtypes

SEVERITYCODE         int64
X                  float64
Y                  float64
OBJECTID             int64
INCKEY               int64
COLDETKEY            int64
REPORTNO            object
STATUS              object
ADDRTYPE            object
INTKEY             float64
LOCATION            object
EXCEPTRSNCODE       object
EXCEPTRSNDESC       object
SEVERITYCODE.1       int64
SEVERITYDESC        object
COLLISIONTYPE       object
PERSONCOUNT          int64
PEDCOUNT             int64
PEDCYLCOUNT          int64
VEHCOUNT             int64
INCDATE             object
INCDTTM             object
JUNCTIONTYPE        object
SDOT_COLCODE         int64
SDOT_COLDESC        object
INATTENTIONIND      object
UNDERINFL           object
WEATHER           category
ROADCOND          category
LIGHTCOND         category
PEDROWNOTGRNT       object
SDOTCOLNUM         float64
SPEEDING            object
ST_COLCODE          object
ST_COLDESC          object
SEGLANEKEY           int64
CROSSWALKKEY         int64
H

In [16]:
X = balanced_df[['WEATHER_cat','ROADCOND_cat','LIGHTCOND_cat']].values

In [17]:
Y = balanced_df['SEVERITYCODE'].values

# Define attributes X and Label Y variables

In [19]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

# kNN ML Model

In [24]:
from sklearn.neighbors import KNeighborsClassifier
k=17
knn = KNeighborsClassifier(n_neighbors = k).fit(X_train,Y_train)
knn_Y_pred = knn.predict(X_test)
knn_Y_pred[0:5]

array([2, 1, 2, 2, 1], dtype=int64)

# kNN ML Model Evaluation

In [52]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(Y_train, knn.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(Y_test, knn_Y_pred))

Train set Accuracy:  0.5573147153598281
Test set Accuracy:  0.5605774188004812


In [56]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, knn_Y_pred)

0.5605774188004812

In [59]:
from sklearn.metrics import f1_score
f1_score(Y_test, knn_Y_pred, average = 'macro')

0.5145090596058421

# Decision Tree ML Model

In [38]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = "entropy", max_depth = 7)
dt.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=7,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [53]:
predTree = dt.predict(X_test)
print (predTree [0:5])
print (Y_test [0:5])

[2 1 1 2 1]
[2 1 2 1 2]


# Decision Tree ML Model Evaluation

In [54]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(Y_test, predTree))

DecisionTrees's Accuracy:  0.5631122185942602


In [57]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, predTree)

0.5631122185942602

In [60]:
from sklearn.metrics import f1_score
f1_score(Y_test, predTree, average = 'macro')

0.5325345336746883

# Logistic Regression ML Model

In [46]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=6, solver='liblinear').fit(X_train,Y_train)
LR

LogisticRegression(C=6, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [49]:
LRyhat = LR.predict(X_test)
LRyhat

array([2, 2, 2, ..., 2, 2, 2], dtype=int64)

In [50]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.47215715, 0.52784285],
       [0.43603401, 0.56396599],
       [0.46429576, 0.53570424],
       ...,
       [0.47215715, 0.52784285],
       [0.46785336, 0.53214664],
       [0.47215715, 0.52784285]])

# Logistic Regression ML Model Evaluation

In [55]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(Y_test, LRyhat)

0.5322649939852209

In [58]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("DecisionTrees's Accuracy: ", metrics.accuracy_score(Y_test, LRyhat))

DecisionTrees's Accuracy:  0.5322649939852209


In [61]:
from sklearn.metrics import f1_score
f1_score(Y_test, LRyhat, average = 'macro')

0.5177287440369664